name: SafeDamageHere
version: ${project.version}
main: me.shakeforprotein.safedamagehere.SafeDamageHere
authors: [ShakeforProtein]
description: Prevents configurable damage in a region.
website: http://play.treebomc.com


commands:
  sdh:
    description: Safe Damage Here Commands
    usage: /<command> <subcommand>